// generated by Fast Light User Interface Designer (fluid) version 1.00

#include "animatoruiwindows.h"
ModelerUIWindows::ModelerUIWindows() {
  Fl_Window* w;
  { Fl_Window* o = m_pwndModelerWnd = new Fl_Window(740, 696, "Model");//add 400 on both length and width//zyc
    w = o;
    o->user_data((void*)(this));
    o->when(FL_WHEN_NEVER);
    { ModelerView* o = m_pwndModelerView = new ModelerView(0, 0, 340, 295, (char *)"ModelerView");
      Fl_Group::current()->resizable(o);
    }
    o->end();
  }
  { Fl_Window* o = m_pwndScoreWnd = new Fl_Window(300, 200, "Score");//add 400 on both length and width//zyc
    w = o;
    o->user_data((void*)(this));
    o->when(FL_WHEN_NEVER);
    { Fl_Box* o = m_pwndBox = new Fl_Box(0, 0, 200, 40, "0");
      o->box(FL_ENGRAVED_BOX);
      o->labelfont(FL_BOLD+FL_ITALIC);
      o->labeltype(FL_NORMAL_LABEL);
      o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
      o->show();
    }
    o->end();
  }
 
}
