// generated by Fast Light User Interface Designer (fluid) version 1.00

#include "animatoruiwindows.h"
ModelerUIWindows::ModelerUIWindows() {
  Fl_Window* w;
  { Fl_Window* o = m_pwndModelerWnd = new Fl_Window(740, 696, "Model");//add 400 on both length and width//zyc
    w = o;
    o->user_data((void*)(this));
    o->when(FL_WHEN_NEVER);
    { ModelerView* o = m_pwndModelerView = new ModelerView(0, 0, 340, 295, (char *)"ModelerView");
      Fl_Group::current()->resizable(o);
    }
    o->end();
  }

  { Fl_Window* o = m_pwndScoreWnd = new Fl_Window(350, 500, "Score");//add 400 on both length and width//zyc
    w = o;
    o->user_data((void*)(this));
    o->when(FL_WHEN_NEVER);
    { 
      Fl_Text_Buffer *buff = m_pwndTxtBuf = new Fl_Text_Buffer();
      Fl_Text_Display* o = m_pwndTxtDis = new Fl_Text_Display(0, 0, 350, 500, "string");
      o->buffer(buff);
      o->show();
      buff->text("Game Start: \n\n\t        [---Instructions---]\n\t|  Use Up, Down, Left, Right   |\n\t|  to control the perspective, |\n\t|  Use w, a, s, d, 1, 2, 3, 4        |\n\t|  to control the stacker]        |\n\n");
    }
    o->end();
  }
 
}
