// generated by Fast Light User Interface Designer (fluid) version 1.00

#ifndef animatoruiwindows_h
#define animatoruiwindows_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Group.H>
#include "modelerview.h"

class ModelerUIWindows {
public:
  ModelerUIWindows();
  Fl_Window *m_pwndModelerWnd;
  Fl_Window *m_pwndScoreWnd;
  Fl_Box *m_pwndBox;
  ModelerView *m_pwndModelerView;
};
#endif
